# Generated by Django 4.0.4 on 2022-05-27 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blow',
            fields=[
                ('blw_id', models.AutoField(primary_key=True, serialize=False)),
                ('blw_nmonico', models.CharField(max_length=1)),
                ('blw_name', models.TextField()),
            ],
            options={
                'db_table': 'blow',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('mov_id', models.AutoField(primary_key=True, serialize=False)),
                ('mov_nmonico', models.CharField(max_length=1)),
                ('mov_name', models.TextField()),
            ],
            options={
                'db_table': 'movement',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('ply_id', models.AutoField(primary_key=True, serialize=False)),
                ('ply_nombre', models.TextField()),
                ('ply_life_point', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'player',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SpecialBlow',
            fields=[
                ('sbw_id', models.AutoField(primary_key=True, serialize=False)),
                ('sbw_name', models.TextField()),
                ('sbw_combination', models.TextField()),
            ],
            options={
                'db_table': 'special_blow',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlayerSpecialBlow',
            fields=[
                ('psb_id', models.AutoField(primary_key=True, serialize=False)),
                ('ply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jrpg.player')),
                ('sbw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jrpg.specialblow')),
            ],
            options={
                'db_table': 'player_special_blow',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Damage',
            fields=[
                ('dmg_id', models.AutoField(primary_key=True, serialize=False)),
                ('dmg_ind_special', models.BooleanField(default=False)),
                ('dmg_point', models.IntegerField()),
                ('blw_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jrpg.blow')),
                ('sbw_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jrpg.specialblow')),
            ],
        ),
    ]
