# Generated by Django 4.0.4 on 2022-05-27 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jrpg', '0002_alter_damage_options_alter_damage_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damage',
            name='blw_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jrpg.blow'),
        ),
        migrations.AlterField(
            model_name='damage',
            name='sbw_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jrpg.specialblow'),
        ),
    ]
