# Generated by Django 4.0.4 on 2022-05-27 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jrpg', '0003_alter_damage_blw_id_alter_damage_sbw_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('gam_id', models.AutoField(primary_key=True, serialize=False)),
                ('gam_datetime', models.DateTimeField(auto_now=True)),
                ('ply_wing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jrpg.player')),
            ],
            options={
                'db_table': 'game',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EventName',
            fields=[
                ('evg_id', models.AutoField(primary_key=True, serialize=False)),
                ('evg_descripcion', models.TextField()),
                ('gam_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jrpg.game')),
            ],
            options={
                'db_table': 'event_game',
                'managed': True,
            },
        ),
    ]
